name: flutter_learning
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  path_provider: ^0.4.0
  json_annotation: ^0.2.2
  http: ^0.11.3+16
  dio: ^1.0.1
  english_words: ^3.1.3

  # To change the version of the gallery assets, edit
  #   //packages/flutter_tools/lib/src/commands/update_packages.dart
  # and run
  #   flutter update-packages --force-upgrade
  flutter_gallery_assets: 0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^0.7.6
  json_serializable: ^0.3.2


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    - res/shops.json
    - images/lake.jpg
    - images/pavlova.jpg
    - images/contact_photo1.jpg
    - images/pic1.jpg
    - images/pic2.jpg
    - images/pic3.jpg
    - images/pic4.jpg
    - images/pic5.jpg
    - images/pic6.jpg
    - images/pic7.jpg
    - images/pic8.jpg
    - images/pic9.jpg
    - images/pic10.jpg
    - images/pic11.jpg
    - images/pic12.jpg
    - images/pic13.jpg
    - images/pic14.jpg
    - images/pic15.jpg
    - images/pic16.jpg
    - images/pic17.jpg
    - images/pic18.jpg
    - images/pic19.jpg
    - images/pic20.jpg
    - images/pic21.jpg
    - images/pic22.jpg
    - images/pic23.jpg
    - images/pic24.jpg
    - images/pic25.jpg
    - images/pic26.jpg
    - images/pic27.jpg
    - images/pic28.jpg
    - images/pic29.jpg
    - images/pic30.jpg
    - packages/flutter_gallery_assets/people/ali_landscape.png
    - packages/flutter_gallery_assets/logos/flutter_white/logo.png
    - packages/flutter_gallery_assets/videos/bee.mp4
    - packages/flutter_gallery_assets/videos/butterfly.mp4
    - packages/flutter_gallery_assets/animated_images/animated_flutter_lgtm.gif
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
    - packages/flutter_gallery_assets/food/image10.jpg
    - packages/flutter_gallery_assets/food/image11.jpg
    - packages/flutter_gallery_assets/food/image12.jpg
    - packages/flutter_gallery_assets/food/image13.jpg
    - packages/flutter_gallery_assets/food/image1.jpg
    - packages/flutter_gallery_assets/food/image2.jpg
    - packages/flutter_gallery_assets/food/image3.jpg
    - packages/flutter_gallery_assets/food/image4.jpg
    - packages/flutter_gallery_assets/food/image5.jpg
    - packages/flutter_gallery_assets/food/image6.jpg
    - packages/flutter_gallery_assets/food/image7.jpg
    - packages/flutter_gallery_assets/food/image8.jpg
    - packages/flutter_gallery_assets/food/image9.jpg
    - packages/flutter_gallery_assets/food/icons/fish.png
    - packages/flutter_gallery_assets/food/icons/healthy.png
    - packages/flutter_gallery_assets/food/icons/main.png
    - packages/flutter_gallery_assets/food/icons/meat.png
    - packages/flutter_gallery_assets/food/icons/quick.png
    - packages/flutter_gallery_assets/food/icons/spicy.png
    - packages/flutter_gallery_assets/food/icons/veggie.png
    - packages/flutter_gallery_assets/logos/pesto/logo_small.png
    - packages/flutter_gallery_assets/places/india_chennai_flower_market.png
    - packages/flutter_gallery_assets/places/india_thanjavur_market.png
    - packages/flutter_gallery_assets/places/india_tanjore_bronze_works.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_merchant.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple.png
    - packages/flutter_gallery_assets/places/india_pondicherry_salt_farm.png
    - packages/flutter_gallery_assets/places/india_chennai_highway.png
    - packages/flutter_gallery_assets/places/india_chettinad_silk_maker.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple_carvings.png
    - packages/flutter_gallery_assets/places/india_chettinad_produce.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_technology.png
    - packages/flutter_gallery_assets/places/india_pondicherry_beach.png
    - packages/flutter_gallery_assets/places/india_pondicherry_fisherman.png
    - packages/flutter_gallery_assets/products/backpack.png
    - packages/flutter_gallery_assets/products/belt.png
    - packages/flutter_gallery_assets/products/cup.png
    - packages/flutter_gallery_assets/products/deskset.png
    - packages/flutter_gallery_assets/products/dress.png
    - packages/flutter_gallery_assets/products/earrings.png
    - packages/flutter_gallery_assets/products/flatwear.png
    - packages/flutter_gallery_assets/products/hat.png
    - packages/flutter_gallery_assets/products/jacket.png
    - packages/flutter_gallery_assets/products/jumper.png
    - packages/flutter_gallery_assets/products/kitchen_quattro.png
    - packages/flutter_gallery_assets/products/napkins.png
    - packages/flutter_gallery_assets/products/planters.png
    - packages/flutter_gallery_assets/products/platter.png
    - packages/flutter_gallery_assets/products/scarf.png
    - packages/flutter_gallery_assets/products/shirt.png
    - packages/flutter_gallery_assets/products/sunnies.png
    - packages/flutter_gallery_assets/products/sweater.png
    - packages/flutter_gallery_assets/products/sweats.png
    - packages/flutter_gallery_assets/products/table.png
    - packages/flutter_gallery_assets/products/teaset.png
    - packages/flutter_gallery_assets/products/top.png
    - packages/flutter_gallery_assets/people/ali.png
    - packages/flutter_gallery_assets/people/square/ali.png
    - packages/flutter_gallery_assets/people/square/peter.png
    - packages/flutter_gallery_assets/people/square/sandra.png
    - packages/flutter_gallery_assets/people/square/stella.png
    - packages/flutter_gallery_assets/people/square/trevor.png
  fonts:
    - family: Raleway
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/raleway/Raleway-Regular.ttf
        - asset: packages/flutter_gallery_assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: packages/flutter_gallery_assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
    - family: AbrilFatface
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/abrilfatface/AbrilFatface-Regular.ttf
    - family: GalleryIcons
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/private/gallery_icons/GalleryIcons.ttf
    - family: GoogleSans
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSans-Bold.ttf
          weight: 700
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSans-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSans-Medium.ttf
          weight: 500
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSans-Regular.ttf
          weight: 400
    - family: GoogleSansDisplay
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSansDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSansDisplay-Bold.ttf
          weight: 700
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSansDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSansDisplay-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSansDisplay-Medium.ttf
          weight: 500
        - asset: packages/flutter_gallery_assets/fonts/private/googlesans/GoogleSansDisplay-Regular.ttf
          weight: 400
